<template>
  <div class="env-setup-panel">
    <div class="scroll-container">
      <!-- 01: Simulation Instance -->
      <SimulationInstanceCard
        :phase="phase"
        :simulationId="simulationId"
        :projectData="projectData"
        :taskId="taskId"
      />

      <!-- 02: Agent Personas -->
      <AgentProfilesSection
        :phase="phase"
        :profiles="profiles"
        :prepareProgress="prepareProgress"
        :expectedTotal="expectedTotal"
        @select-profile="selectedProfile = $event"
      />

      <!-- 03: Dual Platform Config -->
      <SimConfigSection
        :phase="phase"
        :simulationConfig="simulationConfig"
      />

      <!-- 04: Orchestration / Initial Posts -->
      <OrchestrationSection
        :phase="phase"
        :simulationConfig="simulationConfig"
        :profiles="profiles"
      />

      <!-- 05: Readiness & Launch -->
      <SetupReadinessSection
        :phase="phase"
        :simulationConfig="simulationConfig"
        :autoGeneratedRounds="autoGeneratedRounds"
        v-model:useCustomRounds="useCustomRounds"
        v-model:customMaxRounds="customMaxRounds"
        @go-back="$emit('go-back')"
        @start-simulation="handleStartSimulation"
      />
    </div>

    <!-- Logs panel — compacto por padrão -->
    <SystemLogsPanel :logs="systemLogs" :contextId="simulationId" />

    <!-- Profile detail modal -->
    <ProfileDetailPanel
      :profile="selectedProfile"
      @close="selectedProfile = null"
    />
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { useI18n } from 'vue-i18n'

import SimulationInstanceCard from './step2/SimulationInstanceCard.vue'
import AgentProfilesSection   from './step2/AgentProfilesSection.vue'
import SimConfigSection       from './step2/SimConfigSection.vue'
import OrchestrationSection   from './step2/OrchestrationSection.vue'
import SetupReadinessSection  from './step2/SetupReadinessSection.vue'
import ProfileDetailPanel     from './step2/ProfileDetailPanel.vue'
import SystemLogsPanel        from './workspace/SystemLogsPanel.vue'

import {
  prepareSimulation,
  getPrepareStatus,
  getSimulationProfilesRealtime,
  getSimulationConfigRealtime,
} from '../api/simulation'

const { t } = useI18n()

// ── Props & Emits ──────────────────────────────────────────────────────────────
const props = defineProps({
  simulationId: String,
  projectData:  Object,
  graphData:    Object,
  systemLogs:   Array,
})

const emit = defineEmits(['go-back', 'next-step', 'add-log', 'update-status'])

// ── State ─────────────────────────────────────────────────────────────────────
const phase           = ref(0) // 0 init | 1 personas | 2 config | 3 orchestration | 4 ready
const taskId          = ref(null)
const prepareProgress = ref(0)
const currentStage    = ref('')
const profiles        = ref([])
const entityTypes     = ref([])
const expectedTotal   = ref(null)
const simulationConfig = ref(null)
const selectedProfile = ref(null)
const useCustomRounds = ref(false)
const customMaxRounds = ref(40)

// Dedup tracking
let lastLoggedMessage      = ''
let lastLoggedProfileCount = 0
let lastLoggedConfigStage  = ''

// Polling timers
let pollTimer     = null
let profilesTimer = null
let configTimer   = null

// ── Computed ───────────────────────────────────────────────────────────────────
const autoGeneratedRounds = computed(() => {
  const tc = simulationConfig.value?.time_config
  if (!tc?.total_simulation_hours || !tc?.minutes_per_round) return null
  return Math.max(Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round), 40)
})

// systemLogs is passed from parent (SimulationView), re-export for SystemLogsPanel
// Note: The panel renders props.systemLogs directly.

// ── Helpers ───────────────────────────────────────────────────────────────────
const addLog = (msg) => emit('add-log', msg)

const handleStartSimulation = (params = {}) => {
  if (params.maxRounds) {
    addLog(t('log.startSimCustomRounds', { rounds: params.maxRounds }))
  } else {
    addLog(t('log.startSimAutoRounds', { rounds: autoGeneratedRounds.value }))
  }
  emit('next-step', params)
}

// ── Stage watcher ─────────────────────────────────────────────────────────────
watch(currentStage, (newStage) => {
  if (newStage === '生成Agent人设' || newStage === 'generating_profiles') {
    phase.value = 1
  } else if (newStage === '生成模拟配置' || newStage === 'generating_config') {
    phase.value = 2
    if (!configTimer) {
      addLog(t('log.startGeneratingConfig'))
      startConfigPolling()
    }
  } else if (newStage === '准备模拟脚本' || newStage === 'copying_scripts') {
    phase.value = 2
  }
})

// ── Polling: prepare status ───────────────────────────────────────────────────
const startPolling = () => { pollTimer = setInterval(pollPrepareStatus, 2000) }
const stopPolling  = () => { if (pollTimer) { clearInterval(pollTimer); pollTimer = null } }

const pollPrepareStatus = async () => {
  if (!taskId.value && !props.simulationId) return
  try {
    const res = await getPrepareStatus({ task_id: taskId.value, simulation_id: props.simulationId })
    if (!res.success || !res.data) return
    const data = res.data

    prepareProgress.value = data.progress || 0

    if (data.progress_detail) {
      currentStage.value = data.progress_detail.current_stage_name || ''
      const d = data.progress_detail
      const key = `${d.current_stage}-${d.current_item}-${d.total_items}`
      if (key !== lastLoggedMessage && d.item_description) {
        lastLoggedMessage = key
        const info = `[${d.stage_index}/${d.total_stages}]`
        if (d.total_items > 0) {
          addLog(`${info} ${d.current_stage_name}: ${d.current_item}/${d.total_items} - ${d.item_description}`)
        } else {
          addLog(`${info} ${d.current_stage_name}: ${d.item_description}`)
        }
      }
    } else if (data.message && data.message !== lastLoggedMessage) {
      lastLoggedMessage = data.message
      const match = data.message.match(/\[(\d+)\/(\d+)\]\s*([^:]+)/)
      if (match) currentStage.value = match[3].trim()
      addLog(data.message)
    }

    if (data.status === 'completed' || data.status === 'ready' || data.already_prepared) {
      addLog(t('log.prepareComplete'))
      stopPolling()
      stopProfilesPolling()
      await loadPreparedData()
    } else if (data.status === 'failed') {
      addLog(t('log.prepareFailedWithError', { error: data.error || t('common.unknownError') }))
      stopPolling()
      stopProfilesPolling()
    }
  } catch (e) {
    console.warn('prepare poll error:', e)
  }
}

// ── Polling: profiles ─────────────────────────────────────────────────────────
const startProfilesPolling = () => { profilesTimer = setInterval(fetchProfilesRealtime, 3000) }
const stopProfilesPolling  = () => { if (profilesTimer) { clearInterval(profilesTimer); profilesTimer = null } }

const fetchProfilesRealtime = async () => {
  if (!props.simulationId) return
  try {
    const res = await getSimulationProfilesRealtime(props.simulationId, 'reddit')
    if (!res.success || !res.data) return

    profiles.value = res.data.profiles || []
    if (res.data.total_expected) expectedTotal.value = res.data.total_expected

    const types = new Set()
    profiles.value.forEach(p => { if (p.entity_type) types.add(p.entity_type) })
    entityTypes.value = Array.from(types)

    const count = profiles.value.length
    if (count > 0 && count !== lastLoggedProfileCount) {
      lastLoggedProfileCount = count
      const total = expectedTotal.value || '?'
      const latest = profiles.value[count - 1]
      const name = latest?.name || latest?.username || `Agent_${count}`
      if (count === 1) addLog(t('log.startGeneratingAgentProfiles'))
      addLog(t('log.agentProfile', { current: count, total, name, profession: latest?.profession || t('step2.unknownProfession') }))
      if (expectedTotal.value && count >= expectedTotal.value) {
        addLog(t('log.allProfilesComplete', { count }))
      }
    }
  } catch (e) {
    console.warn('profiles poll error:', e)
  }
}

// ── Polling: config ───────────────────────────────────────────────────────────
const startConfigPolling = () => { configTimer = setInterval(fetchConfigRealtime, 2000) }
const stopConfigPolling  = () => { if (configTimer) { clearInterval(configTimer); configTimer = null } }

const fetchConfigRealtime = async () => {
  if (!props.simulationId) return
  try {
    const res = await getSimulationConfigRealtime(props.simulationId)
    if (!res.success || !res.data) return
    const data = res.data

    if (data.generation_stage && data.generation_stage !== lastLoggedConfigStage) {
      lastLoggedConfigStage = data.generation_stage
      if (data.generation_stage === 'generating_profiles') addLog(t('log.generatingAgentProfileConfig'))
      else if (data.generation_stage === 'generating_config') addLog(t('log.generatingLLMConfig'))
    }

    if (data.config_generated && data.config) {
      simulationConfig.value = data.config
      addLog(t('log.configComplete'))

      if (data.summary) {
        addLog(t('log.configSummaryAgents',   { count: data.summary.total_agents }))
        addLog(t('log.configSummaryHours',    { hours: data.summary.simulation_hours }))
        addLog(t('log.configSummaryPosts',    { count: data.summary.initial_posts_count }))
        addLog(t('log.configSummaryTopics',   { count: data.summary.hot_topics_count }))
        addLog(t('log.configSummaryPlatforms',{
          twitter: data.summary.has_twitter_config ? '✓' : '✗',
          reddit:  data.summary.has_reddit_config  ? '✓' : '✗',
        }))
      }
      if (data.config.time_config) {
        const tc = data.config.time_config
        addLog(t('log.timeConfigDetail', {
          minutes: tc.minutes_per_round,
          rounds:  Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round),
        }))
      }
      if (data.config.event_config?.narrative_direction) {
        const n = data.config.event_config.narrative_direction
        addLog(t('log.narrativeDirection', { direction: n.length > 50 ? n.slice(0, 50) + '…' : n }))
      }

      stopConfigPolling()
      phase.value = 4
      addLog(t('log.envSetupComplete'))
      emit('update-status', 'completed')
    }
  } catch (e) {
    console.warn('config poll error:', e)
  }
}

// ── Data loading ──────────────────────────────────────────────────────────────
const loadPreparedData = async () => {
  phase.value = 2
  addLog(t('log.loadingExistingConfig'))

  await fetchProfilesRealtime()
  addLog(t('log.loadedAgentProfiles', { count: profiles.value.length }))

  try {
    const res = await getSimulationConfigRealtime(props.simulationId)
    if (res.success && res.data?.config_generated && res.data.config) {
      simulationConfig.value = res.data.config
      addLog(t('log.configLoadSuccess'))
      if (res.data.summary) {
        addLog(t('log.configSummaryAgents',   { count: res.data.summary.total_agents }))
        addLog(t('log.configSummaryHours',    { hours: res.data.summary.simulation_hours }))
        addLog(t('log.configSummaryPostsAlt', { count: res.data.summary.initial_posts_count }))
      }
      addLog(t('log.envSetupComplete'))
      phase.value = 4
      emit('update-status', 'completed')
    } else {
      addLog(t('log.configGenerating'))
      startConfigPolling()
    }
  } catch (err) {
    addLog(t('log.loadConfigFailed', { error: err.message }))
    emit('update-status', 'error')
  }
}

const startPrepareSimulation = async () => {
  if (!props.simulationId) {
    addLog(t('log.errorMissingSimId'))
    emit('update-status', 'error')
    return
  }

  phase.value = 1
  addLog(t('log.simInstanceCreated', { id: props.simulationId }))
  addLog(t('log.preparingSimEnv'))
  emit('update-status', 'processing')

  try {
    const res = await prepareSimulation({
      simulation_id:           props.simulationId,
      use_llm_for_profiles:    true,
      parallel_profile_count:  5,
    })

    if (res.success && res.data) {
      if (res.data.already_prepared) {
        addLog(t('log.detectedExistingPrep'))
        await loadPreparedData()
        return
      }

      taskId.value = res.data.task_id
      addLog(t('log.prepareTaskStarted'))
      addLog(t('log.prepareTaskId', { taskId: res.data.task_id }))

      if (res.data.expected_entities_count) {
        expectedTotal.value = res.data.expected_entities_count
        addLog(t('log.zepEntitiesFound', { count: res.data.expected_entities_count }))
        if (res.data.entity_types?.length) {
          addLog(t('log.entityTypes', { types: res.data.entity_types.join(', ') }))
        }
      }

      addLog(t('log.startPollingProgress'))
      startPolling()
      startProfilesPolling()
    } else {
      addLog(t('log.prepareFailed', { error: res.error || t('common.unknownError') }))
      emit('update-status', 'error')
    }
  } catch (err) {
    addLog(t('log.prepareException', { error: err.message }))
    emit('update-status', 'error')
  }
}

// ── Lifecycle ──────────────────────────────────────────────────────────────────
onMounted(() => {
  if (props.simulationId) {
    addLog(t('log.step2Init'))
    startPrepareSimulation()
  }
})

onUnmounted(() => {
  stopPolling()
  stopProfilesPolling()
  stopConfigPolling()
})
</script>

<style scoped>
.env-setup-panel {
  height: 100%;
  display: flex;
  flex-direction: column;
  background: #F7F7F7;
  font-family: 'Space Grotesk', 'Noto Sans SC', system-ui, sans-serif;
  overflow: hidden;
}

.scroll-container {
  flex: 1;
  overflow-y: auto;
  padding: 20px 18px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.scroll-container::-webkit-scrollbar { width: 4px; }
.scroll-container::-webkit-scrollbar-thumb { background: #DDD; border-radius: 2px; }
</style>
