<template>
  <div class="setup-card" :class="{ 'card--active': phase >= 4, 'card--pending': phase < 4 }">
    <div class="card-head">
      <div class="card-label">
        <span class="card-num">05</span>
        <span class="card-title">{{ $t('step2.setupComplete') }}</span>
      </div>
      <span class="card-badge" :class="phase >= 4 ? 'badge--active' : 'badge--pending'">
        {{ phase >= 4 ? $t('step1.inProgress') : $t('common.pending') }}
      </span>
    </div>

    <div class="card-body">
      <p class="api-route">POST /api/simulation/start</p>
      <p class="card-desc">{{ $t('step2.setupCompleteDesc') }}</p>

      <!-- Configuração de rounds — só aparece quando ready -->
      <div v-if="simulationConfig && autoGeneratedRounds" class="rounds-section">
        <div class="rounds-head">
          <div class="rounds-info">
            <span class="rounds-title">{{ $t('step2.roundsConfig') }}</span>
            <span class="rounds-desc">
              {{ $t('step2.roundsConfigDesc', {
                hours: simulationConfig?.time_config?.total_simulation_hours || '—',
                minutesPerRound: simulationConfig?.time_config?.minutes_per_round || '—'
              }) }}
            </span>
          </div>
          <label class="toggle-label">
            <input type="checkbox" v-model="localCustom" class="toggle-input" />
            <span class="toggle-track"><span class="toggle-thumb" /></span>
            <span class="toggle-text">{{ $t('step2.customToggle') }}</span>
          </label>
        </div>

        <Transition name="fade" mode="out-in">
          <div v-if="localCustom" key="custom" class="rounds-body">
            <div class="rounds-display">
              <span class="rounds-num">{{ localMaxRounds }}</span>
              <span class="rounds-unit">{{ $t('step2.roundsUnit') }}</span>
              <span class="rounds-est">≈ {{ Math.round(localMaxRounds * 0.6) }}min</span>
            </div>
            <div class="range-wrap">
              <input
                type="range"
                v-model.number="localMaxRounds"
                min="10"
                :max="autoGeneratedRounds"
                step="5"
                class="range-input"
                :style="{ '--fill': fillPct }"
              />
              <div class="range-marks">
                <span>10</span>
                <span
                  class="mark-rec"
                  :class="{ active: localMaxRounds === 40 }"
                  @click="localMaxRounds = 40"
                >{{ $t('step2.recommendedRounds', { rounds: 40 }) }}</span>
                <span>{{ autoGeneratedRounds }}</span>
              </div>
            </div>
          </div>

          <div v-else key="auto" class="rounds-auto">
            <div class="auto-num">
              <span class="rounds-num">{{ autoGeneratedRounds }}</span>
              <span class="rounds-unit">{{ $t('step2.roundsUnit') }}</span>
            </div>
            <p class="auto-tip" @click="localCustom = true">
              {{ $t('step2.customTip') }} →
            </p>
          </div>
        </Transition>
      </div>

      <!-- Ações -->
      <div class="action-row">
        <button class="btn-secondary" @click="$emit('go-back')">
          ← {{ $t('step2.backToGraphBuild') }}
        </button>
        <button
          class="btn-primary"
          :disabled="phase < 4"
          @click="handleStart"
        >
          {{ $t('step2.startDualWorldSim') }} →
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'

const props = defineProps({
  phase:              { type: Number,  required: true },
  simulationConfig:   { type: Object,  default: null },
  autoGeneratedRounds:{ type: Number,  default: null },
  useCustomRounds:    { type: Boolean, default: false },
  customMaxRounds:    { type: Number,  default: 40 },
})

const emit = defineEmits(['go-back', 'start-simulation', 'update:useCustomRounds', 'update:customMaxRounds'])

const localCustom    = ref(props.useCustomRounds)
const localMaxRounds = ref(props.customMaxRounds)

// Sync child → parent
watch(localCustom,    (v) => emit('update:useCustomRounds', v))
watch(localMaxRounds, (v) => emit('update:customMaxRounds', v))

// Sync parent → child (caso o pai mude externamente, ex: remount)
watch(() => props.useCustomRounds, (v) => { if (v !== localCustom.value) localCustom.value = v })
watch(() => props.customMaxRounds, (v) => { if (v !== localMaxRounds.value) localMaxRounds.value = v })

// Guard: quando autoGeneratedRounds fica disponível ou muda,
// clamp localMaxRounds para não exceder o máximo do slider.
watch(() => props.autoGeneratedRounds, (max) => {
  if (max !== null && localMaxRounds.value > max) {
    localMaxRounds.value = max
  }
})

const fillPct = computed(() => {
  if (!props.autoGeneratedRounds) return '0%'
  return ((localMaxRounds.value - 10) / (props.autoGeneratedRounds - 10)) * 100 + '%'
})

const handleStart = () => {
  const params = {}
  if (localCustom.value) params.maxRounds = localMaxRounds.value
  emit('start-simulation', params)
}
</script>

<style scoped>
.setup-card {
  background: #fff;
  border: 1px solid #EBEBEB;
  border-radius: 10px;
  overflow: hidden;
  transition: border-color 0.2s, opacity 0.2s;
}
.setup-card.card--active  { border-color: #CCCCCC; }
.setup-card.card--pending { opacity: 0.5; }

.card-head {
  display: flex; align-items: center; justify-content: space-between;
  padding: 14px 18px; border-bottom: 1px solid #F0F0F0;
}
.card-label { display: flex; align-items: center; gap: 10px; }
.card-num { font-family: 'JetBrains Mono', monospace; font-size: 11px; font-weight: 700; color: #CCCCCC; }
.card-title { font-size: 13px; font-weight: 700; color: #1A1A1A; }

.card-badge { font-size: 10.5px; font-weight: 700; padding: 3px 10px; border-radius: 20px; }
.badge--active  { background: #FFF3EE; color: #D44B00; }
.badge--pending { background: #F5F5F5; color: #AAAAAA; }

.card-body { padding: 16px 18px; display: flex; flex-direction: column; gap: 16px; }
.api-route { font-family: 'JetBrains Mono', monospace; font-size: 10px; color: #AAAAAA; margin: 0; }
.card-desc  { font-size: 12.5px; color: #555; margin: 0; line-height: 1.55; }

/* Rounds section */
.rounds-section {
  background: #F8F8F8; border-radius: 8px; padding: 14px 16px;
  display: flex; flex-direction: column; gap: 14px;
}
.rounds-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; }
.rounds-info { display: flex; flex-direction: column; gap: 3px; }
.rounds-title { font-size: 13px; font-weight: 700; color: #1A1A1A; }
.rounds-desc  { font-size: 11px; color: #888; line-height: 1.5; }

/* Toggle */
.toggle-label { display: flex; align-items: center; gap: 8px; cursor: pointer; flex-shrink: 0; }
.toggle-input { display: none; }
.toggle-track {
  width: 34px; height: 18px; background: #DDD; border-radius: 9px;
  position: relative; transition: background 0.2s; flex-shrink: 0;
}
.toggle-thumb {
  position: absolute; top: 2px; left: 2px;
  width: 14px; height: 14px; border-radius: 50%;
  background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.2);
  transition: transform 0.2s;
}
.toggle-input:checked ~ .toggle-track { background: #1A1A1A; }
.toggle-input:checked ~ .toggle-track .toggle-thumb { transform: translateX(16px); }
.toggle-text { font-size: 11.5px; color: #555; font-weight: 500; }

/* Rounds display */
.rounds-body { display: flex; flex-direction: column; gap: 10px; }
.rounds-display { display: flex; align-items: baseline; gap: 6px; }
.rounds-num { font-family: 'JetBrains Mono', monospace; font-size: 28px; font-weight: 800; color: #1A1A1A; }
.rounds-unit { font-size: 13px; color: #888; }
.rounds-est { font-size: 11px; color: #AAAAAA; margin-left: 8px; }

/* Range input */
.range-wrap { display: flex; flex-direction: column; gap: 6px; }
.range-input {
  -webkit-appearance: none;
  width: 100%; height: 4px;
  background: linear-gradient(to right, #1A1A1A var(--fill, 0%), #E0E0E0 var(--fill, 0%));
  border-radius: 2px; outline: none; cursor: pointer;
}
.range-input::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 14px; height: 14px; border-radius: 50%;
  background: #1A1A1A; cursor: pointer;
  box-shadow: 0 1px 3px rgba(0,0,0,0.25);
}
.range-marks {
  display: flex; justify-content: space-between; align-items: center;
  position: relative; font-size: 10px; color: #AAAAAA;
  font-family: 'JetBrains Mono', monospace;
}
.mark-rec {
  cursor: pointer; font-size: 10px; color: #888;
  background: #E8E8E8; padding: 1px 6px; border-radius: 3px;
  transition: background 0.15s;
}
.mark-rec.active { background: #1A1A1A; color: #fff; }
.mark-rec:hover  { background: #D0D0D0; }

/* Auto */
.rounds-auto { display: flex; align-items: center; gap: 16px; }
.auto-num { display: flex; align-items: baseline; gap: 6px; }
.auto-tip {
  font-size: 11.5px; color: #999; cursor: pointer; margin: 0;
  text-decoration: underline; text-underline-offset: 2px;
  transition: color 0.15s;
}
.auto-tip:hover { color: #333; }

/* Action row */
.action-row { display: flex; gap: 10px; }
.btn-secondary {
  flex: 1; padding: 11px 0; border: 1.5px solid #E0E0E0;
  background: #fff; border-radius: 8px; font-size: 13px; font-weight: 600;
  color: #555; cursor: pointer; transition: border-color 0.15s, color 0.15s;
}
.btn-secondary:hover { border-color: #AAAAAA; color: #1A1A1A; }

.btn-primary {
  flex: 2; padding: 11px 0; border: none;
  background: #1A1A1A; border-radius: 8px; font-size: 13px; font-weight: 700;
  color: #fff; cursor: pointer; letter-spacing: 0.2px;
  transition: background 0.15s, opacity 0.15s;
}
.btn-primary:hover:not(:disabled) { background: #333; }
.btn-primary:disabled { opacity: 0.35; cursor: not-allowed; }

/* Fade transition */
.fade-enter-active, .fade-leave-active { transition: opacity 0.2s; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>
